# Generated by Django 4.1.5 on 2023-01-19 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_autor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pelicula',
            options={'verbose_name': 'pelicula', 'verbose_name_plural': 'peliculas'},
        ),
        migrations.AddField(
            model_name='pelicula',
            name='imagen',
            field=models.ImageField(default='profile_image/descarga.png', upload_to='profile_image'),
        ),
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='avatar')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blog.pelicula')),
            ],
        ),
    ]
