# Generated by Django 4.1.5 on 2023-01-19 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_alter_pelicula_options_pelicula_imagen_avatar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pelicula',
            options={},
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='avatar'),
        ),
        migrations.DeleteModel(
            name='Avatar',
        ),
    ]
