# Generated by Django 4.1.5 on 2023-01-22 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0003_alter_avatar_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='imagen',
            field=models.ImageField(default=1, upload_to='avatar'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='avatar',
        ),
    ]
