# Generated by Django 4.1.5 on 2023-01-22 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0006_remove_usuario_imagen_avatar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
