# Generated by Django 4.1.5 on 2023-01-22 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0007_delete_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='avatar',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='avatar'),
        ),
    ]
