# Generated by Django 4.1.5 on 2023-01-23 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0008_avatar_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='profile_image',
            field=models.ImageField(default=1, upload_to='avatar'),
            preserve_default=False,
        ),
    ]
