# Generated by Django 4.1.5 on 2023-01-23 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0009_alter_avatar_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avatar',
            old_name='profile_image',
            new_name='imagen',
        ),
    ]
